// Mutations list
export enum MutationNames {
  // SET_COUNTER = "SET_COUNTER",
  SET_USER = "SET_USER",
  ADD_USER = "ADD_USER",
  SHOW_GRAPHIC = "SHOW_GRAPHIC",
  // SETTERS
  SET_FIRSTNAME = "SET_FIRSTNAME",
  SET_LASTNAME = "SET_LASTNAME",
  SET_EMAIL = "SET_EMAIL",
  SET_USERNAME = "SET_USERNAME",
  SET_AGE = "SET_AGE",
  // SORTS
  BUBBLE_SORT = "BUBBLE_SORT",
  SET_ERROR = "SET_ERROR",
  QUICK_SORT = "QUICK_SORT",
  // SPEADS
  SET_SPEADS = "SET_SPEADS",
}

// Actions list
export enum ActionNames {
  // GET_COUTNER_ASYNC = "GET_COUTNER_ASYNC",
  USER_REQUEST = "USER_REQUEST",
}
